expose_php = 0
date.timezone = UTC

; https://symfony.com/doc/current/performance.html
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; OPcache : indispensable au mode worker
opcache.enable = 1
opcache.enable_cli = 1
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256

; APCu (cache applicatif / metadata Doctrine)
apc.enable_cli = 1
