; Réglages spécifiques à la production
opcache.preload_user = root
opcache.preload = /app/config/preload.php

; Le code ne change pas en production : on désactive la revalidation
opcache.validate_timestamps = 0

display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
