; Réglages spécifiques au développement
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Xdebug (activé via XDEBUG_MODE dans compose.override.yaml)
xdebug.client_host = host.docker.internal
xdebug.discover_client_host = 1
xdebug.start_with_request = trigger
